### ISSUE TITLE
[Feature Request]: Add Cloud9 to Extended Info

### ISSUE THREAD

**Issue by FelixSmtt** [henrikfroehling/Trakt.NET#670]
### Feature description

The IOS Trakt App uses the Cloud9 key to receive image links from tmdb.

https://api.trakt.tv/search/movie,show?extended=cloud9,full&limit=20&page=1&query=Hangover

This will add the images key to the result dictionary. Like this:

"images": {
                "fanart": [
                    "image.tmdb.org/t/p/w1280/2o0PKGmnSgCGkzoSePNAqse8Ure.jpg",
                    "walter-r2.trakt.tv/images/movies/000/011/534/fanarts/medium/ad82dc5ed2.jpg.webp"
                ],
                "poster": [
                    "image.tmdb.org/t/p/w342/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
                    "walter-r2.trakt.tv/images/movies/000/011/534/posters/thumb/87e9da7505.jpg.webp"
                ],
                "logo": [
                    "assets.fanart.tv/fanart/movies/18785/hdmovielogo/the-hangover-51a651e4a24ce.png",
                    "walter-r2.trakt.tv/images/movies/000/011/534/logos/medium/e3242df874.png.webp"
                ],
                "clearart": [
                    "assets.fanart.tv/fanart/movies/18785/hdmovieclearart/the-hangover-5627569aa6c6d.png",
                    "walter-r2.trakt.tv/images/movies/000/011/534/cleararts/medium/97a5556cec.png.webp"
                ],
                "banner": [
                    "assets.fanart.tv/fanart/movies/18785/moviebanner/the-hangover-51d1e428bce7e.jpg",
                    "walter-r2.trakt.tv/images/movies/000/011/534/banners/medium/fdf3f2264e.jpg.webp"
                ],
                "thumb": [
                    "assets.fanart.tv/fanart/movies/18785/moviethumb/the-hangover-51d1e44f41f42.jpg",
                    "walter-r2.trakt.tv/images/movies/000/011/534/thumbs/medium/6db24bbf5a.jpg.webp"
                ]
            }

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by henrikfroehling** [comment]
This library is intended to only support the officially documented Trakt API.
`cloud9` as an option for the extended info is nowhere mentioned there.
Also testing your given URL with the `cloud9` extended info in Postman does not return additional data about TMDb image URLs.

Because there is a AWS cloud service called "Cloud9", my conclusion is that this must be a specific implementation in the Trakt iOS app.

So, I won't add this flag.

Edit: Something like this is already planned in a different way in #158
